version: 0.0
os: linux
files:
  - source: scripts/
    destination: /opt/currency-exchange-api/scripts/
    overwrite: true
  - source: currency-exchange-api.jar
    destination: /opt/currency-exchange-api/currency-exchange-api.jar
    overwrite: true
  - source: application.properties
    destination: /opt/currency-exchange-api/application.properties
    overwrite: true
  - source: secret.properties
    destination: /opt/currency-exchange-api/secret.properties
    overwrite: true
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ec2-user
