version: 0.0
os: linux
files:
  - source: scripts/
    destination: /opt/currency-exchange-api/scripts/
    overwrite: true
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  ApplicationStop:
    - location: /opt/currency-exchange-api/scripts/application_stop.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: /opt/currency-exchange-api/scripts/before_install.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: /opt/currency-exchange-api/scripts/after_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: /opt/currency-exchange-api/scripts/application_start.sh
      timeout: 300
      runas: ec2-user
