name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  S3BUCKET: deployment-bucket-currency
  CODEDEPLOY_APPLICATION: currency-api-codeploy
  CODEDEPLOY_DEPLOYMENT_GROUP: currency-exchange-api-deployment

jobs:
  build_and_deploy:
    name: Build Docker Image and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t veyg/currency-exchange-api .
          docker save -o deployment/docker-image.tar.gz veyg/currency-exchange-api

      - name: Move Docker Image to Deployment Folder
        run: |
          if [ ! -d "deployment" ]; then
            mkdir deployment
          fi
          mv deployment/docker-image.tar.gz deployment/
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload Docker Image to S3
        run: aws s3 cp deployment/docker-image.tar.gz s3://${{ env.S3BUCKET }}
      
      - name: Create Deployment
        run: |
          echo "Deploying branch ${{ env.GITHUB_REF }} to ${{ env.CODEDEPLOY_DEPLOYMENT_GROUP }}"
          aws deploy create-deployment \
            --application-name ${{ env.CODEDEPLOY_APPLICATION }} \
            --deployment-group-name ${{ env.CODEDEPLOY_DEPLOYMENT_GROUP }} \
            --s3-location bucket=${{ env.S3BUCKET }},bundleType=zip,key=docker-image.tar.gz,versionLabel=$(git rev-parse HEAD),fileExistsBehavior=OVERWRITE \
            --ignore-application-stop-failures
