name: Deploy to EC2

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          java-package: 'jdk'
          distribution: 'adopt'

      - name: Build and Package
        run: mvn clean package

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ec2-13-49-66-210.eu-north-1.compute.amazonaws.com
          username: ec2-user
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          script: |
            ssh-keyscan -H ec2-13-49-66-210.eu-north-1.compute.amazonaws.com >> ~/.ssh/known_hosts
            ssh ec2-user@ec2-13-49-66-210.eu-north-1.compute.amazonaws.com 'sudo systemctl stop currency-exchange-api-1.0.0.jar'
            scp target/currency-exchange-api-1.0.0.jar ec2-user@ec2-13-49-66-210.eu-north-1.compute.amazonaws.com:currency-exchange-api-1.0.0.jar
            ssh ec2-user@ec2-13-49-66-210.eu-north-1.compute.amazonaws.com 'sudo systemctl start currency-exchange-api-1.0.0.jar'